### PR TITLE
 ACM-9145 Fix clustercurator upgrade for imported clusters MCE 2.4

### PR DESCRIPTION
**Pull request by fxiang1**
https://issues.redhat.com/browse/ACM-9145

- Fix clustercurator upgrade for imported clustersFeng import

### CODE REVIEW

**Review by mikeshng — APPROVED** [review]
/approve

/lgtm

**Comment by fxiang1** [comment]
Thanks @mikeshng. Wondering if you can also merge this PR?

Looks like Roke merged some empty commits without dco-signoff that's causing some issues.

**Comment by mikeshng** [comment]
@fxiang1 oops I missed your message. Let's merge this when we get back from holidays to not have some accidental surprises.

**Comment by fxiang1** [comment]
Sounds good. Thanks @mikeshng

**Pull request merged**
