### PR TITLE
ACM-9334 Backport non-recommended version upgrade

### PR DESCRIPTION
**Pull request by fxiang1**
https://issues.redhat.com/browse/ACM-9334

- Backport non-recommended version upgrade

### CODE REVIEW

**Comment by mikeshng** [comment]
@fxiang1 

Can we go into those individual PRs and put in a comment like:

```
/cherrypick backplane-2.3
```

and get the bot do it for us?

**Comment by fxiang1** [comment]
@mikeshng Thanks for taking a look.

> Backport non-recommended version upgrade

For this one I tried cherry picking it didn't work. So I'm manually backporting see https://github.com/stolostron/cluster-curator-controller/pull/195#issuecomment-2077598390

> Add retry when setting clusterversion

This is a brand new bug recently reported by Amadeus so there's no existing PR to cherry pick from.

**Review by mikeshng — APPROVED** [review]
/lgtm

It looks the same as https://github.com/stolostron/cluster-curator-controller/pull/195 so I didn't go through the logic again.

CC @xiangjingli @rokej if you guys want to take an extra look

**Comment by fxiang1** [comment]
Thanks @mikeshng !

**Pull request merged**
