### PR TITLE
Remove ns deletion job

### PR DESCRIPTION
**Pull request by qiujian16**
it is already handled in import controller

Signed-off-by: Jian Qiu <jqiu@redhat.com>

### CODE REVIEW

**Comment by qiujian16** [comment]
https://github.com/stolostron/backlog/issues/22374

**Comment by jnpacker** [comment]
This was added because the ManagedCluster delete at the time wasn't clearing out the namespace, so we may need QE to try this.

**Comment by jnpacker** [comment]
Also if someone detaches the cluster, but doesn't delete it, will the namespace still be removed later when the ClusterDeployment is deleted?

**Comment by qiujian16** [comment]
if managedcluster is 

> Also if someone detaches the cluster, but doesn't delete it, will the namespace still be removed later when the ClusterDeployment is deleted?

if managedcluster is deleted, the ns will finally be removed when clusterdeploymenet is deleted. (unless the existence of infraenv). I need to confirm this with @zhiweiyin318 tomorrow.

**Pull request merged**
